parameters:
    checkdomain.telecash.class: Checkdomain\TeleCash\TeleCash

services:
    checkdomain.telecash.telecash:
        class: %checkdomain.telecash.class%
        arguments:
            - %checkdomain_tele_cash.service_url%
            - %checkdomain_tele_cash.api.user%
            - %checkdomain_tele_cash.api.pass%
            - %checkdomain_tele_cash.client_cert_path%
            - %checkdomain_tele_cash.client_key.path%
            - %checkdomain_tele_cash.client_key.pass_phrase%
            - %checkdomain_tele_cash.server_cert_path%
